'\" t
.\"     Title: re-client
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/22/2014
.\"    Manual: Release Engine
.\"    Source: Release Engine Client 0.0.1
.\"  Language: English
.\"
.TH "RE\-CLIENT" "1" "05/22/2014" "Release Engine Client 0\&.0\&." "Release Engine"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
re-client \- Client utility for the Release Engine
.SH "SYNOPSIS"
.sp
re\-client [\-h] [\-d] [\-p PROJECT] [\-i ID]
.SH "DESCRIPTION"
.sp
Utilities for interacting with the Release Engine\&. Supports creating, reading, updating, and deleting playbooks\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show the help message
.RE
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
Enable debugging output
.RE
.PP
\fB\-p\fR \fIPROJECT\fR, \fB\-\-project\fR=\fIPROJECT\fR
.RS 4
Set default
\fIPROJECT\fR
.RE
.PP
\fB\-i\fR \fIID\fR, \fB\-\-id\fR=\fIID\fR
.RS 4
Set default playbook
\fIID\fR
.RE
.SH "COMMANDS"
.sp
Launching \fBre\-client\fR brings you into a command prompt\&. There are several options to select from, they are self\-explanatory:
.sp
.if n \{\
.RS 4
.\}
.nf
0) Get all playbooks ever
1) Get all playbooks for a project
2) Get a single playbook for a project
3) Update a playbook
4) Delete a playbook
5) Create a new playbook
6) Start a deployment (without dynamic variables)
7) Quit
.fi
.if n \{\
.RE
.\}
.sp
The \fBre\-client\fR prompt is \fBreadline\fR enabled\&. This means it supports line editing and command history if your platform has \fBreadline\fR support\&.
.sp
The \fIGet\fR commands display the requested documents in \fBless\fR\&. The \fIUpdate\fR and \fICreate\fR commands launch an editor\&. If \fBEDITOR\fR is not defined in your shell the editor defaults to \fBemacs\fR\&. You can set this permenantly to something else by exporting \fBEDITOR\fR in your shell rc file:
.sp
.if n \{\
.RS 4
.\}
.nf
# ~/\&.bashrc
export EDITOR=nano
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
The Release Engine was originally written by the \fBInception\fR team at Red Hat\&.
.sp
See the AUTHORS file (or the git logs) for a complete list of contributors\&.
.sp
This man page was originally written by Tim Bielawa <tbielawa@redhat\&.com>\&.
.SH "FILES"
.PP
\fB~/\&.reclient\&.conf\fR
.RS 4
reclient configuration file
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
\fBEDITOR\fR
.RS 4
Default editor choice when updating or creating new playbooks\&.
.RE
.SH "COPYRIGHT"
.sp
Copyright \(co 2014, Red Hat, Inc\&.\&.
.sp
re\-client is released under the terms of the AGPLv3 license\&.
.SH "SEE ALSO"
.sp
\fBre\-core\fR(1), \fBre\-rest\fR(1), \fBre\-logger\fR(1), \fBre\-worker\fR(1)
.sp
\fBThe Inception GitHub Organization\fR \(em https://github\&.com/RHInception
